apiVersion: 1
datasources:

  - name: Prometheus
    uid: prometheusuid
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    uid: lokiuid
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Tempo
    uid: tempouid
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
